13回目の課題提出
ryuichimatsuyama/RaiseTech pull request #9
Opened 2024-05-20 19:49 UTC by ryuichimatsuyama

circleCIにcloudformation,ansible,serverspecの処理を追加しました。

2024-05-22 06:56 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！
実装自体に違和感はないので、分離だけですね！

2024-05-22 06:56 UTC, MasatoshiMizumoto commented on .circleci/config.yml
以下お願いします！！
- cfn-lintは消さない
  - 静的解析は開発で推奨
- CloudFormationとAnsible、Serverspecは別々のジョブにする
  - マシン作成とOS設定、テストは基本的に分離することが望ましい

2024-05-22 21:33 UTC, ryuichimatsuyama commented on .circleci/config.yml
下記対応しました。

- cfn-lint追加
-  CloudFormationとAnsible、Serverspecを別々のジョブにする

2024-05-23 00:56 UTC, MasatoshiMizumoto requested changes
コメント入れさせていただきました！

2024-05-23 00:56 UTC, MasatoshiMizumoto commented on .circleci/config.yml
> +      - create_resources_cloudformation
これは必要ですかね？
前のジョブが成功していることを前提とするなら、このジョブには入れない方が適切だと思います！

2024-05-23 00:56 UTC, MasatoshiMizumoto commented on .circleci/config.yml
> +      - create_resources_cloudformation
これも同じく必要か確認ください！
（テストなのにジョブを単体実行したらリソースができあがってしまう懸念。できあがったリソースをテストするためであり、リソースがなかったら失敗するのが期待では）

2024-05-23 10:00 UTC, ryuichimatsuyama commented on .circleci/config.yml
> +      - create_resources_cloudformation
セキュリティグループを更新する処理(update-stack)を追加しました。
また、セキュリティグループを頻繁に更新するため、templateをセキュリティグループとVPCとそれ以外で分割しました。

2024-05-23 10:07 UTC, MasatoshiMizumoto approved these changes
LGTMです！

2024-05-23 10:16 UTC, merged